MONGO_DATABASE = 'nettruyen'
MONGODB_SERVER = 'localhost'
MONGODB_PORT = 27017
MONGODB_COLLECTION_MANGAS = 'mangas'
MONGODB_COLLECTION_KINDS = 'kinds'
MONGODB_COLLECTION_KIND_MANGAS = 'kind_mangas'
MONGODB_COLLECTION_AUTHORS = 'authors'
MONGODB_COLLECTION_CHAPTERS = 'chapters'

